### ISSUE TITLE
Trying to understand...

### ISSUE THREAD

**Issue by jbramwell** [XpiritBV/Xpirit.Vsts.Build.Zip#3]
If I specify two folders in the "Directories to ZIP" parameter, e.g.:

```
$(build.sourcesDirectory)\Project-1\bin\Release
$(build.sourcesDirectory)\Project-2\bin\Release
```

Does it create one or two ZIP files? What is the ZIP file named and where is it located? I want to be able to pick up the ZIP file and do something with it.

  --- Thanks, Jeff

**Comment by pgroene** [comment]
Hi Jeff, you do not need to add the $(build.sourcesDirectory). It is added in the code.

Project-1\bin\Release
Project-2\bin\Release

Will create 2 zip files:

Project-1\bin\Release.zip
Project-2\bin\Release.zip

-- Peter

**Comment by jbramwell** [comment]
Peter,

Thanks for the prompt reply! That helps a lot.

Quick question... Any chance of adding the ability to create a single ZIP file (with multiple folders in it)? My intent is to publish a single ZIP file to GitHub as a release and I'd rather publish 1 file vs. multiple.

  --- Thanks again, Jeff

**Comment by pgroene** [comment]
The many to one is not supported at this moment, I'll put it on my list. However, you can first copy the directories to one directory and the zip the directory in the mean time.

**Comment by jbramwell** [comment]
Yeah, that is what I am working to do now. It'd just be nice to skip the intermediary step, if possible :-)

  --- Thanks again, Jeff

**Comment by jbramwell** [comment]
OK, I have one more question that maybe you can help with... I am zipping up the following folder:

```
$(Build.ArtifactStagingDirectory)
```

This is the same folder I am publishing back to VSTS as the "artifacts" upload. I am able to verify that this folder has several files/folders within it by downloading the uploaded ZIP file from VSTS.

However, I can't seem to find the right place to locate the resulting ZIP file. I've tried the following paths but they both seem to fail:

```
$(build.sourcesDirectory)\**\Release.zip
$(Agent.BuildDirectory)\**\Release.zip
**\Release.zip
```

The log file (for the Zip Directories step) shows the ZIP file being created here:

```
2016-03-20T20:07:50.6025060Z Item C:\a\1\a to zip
```

This makes me think that the second example should have worked; However, it's not finding the ZIP file.

Any ideas as to how I should go about getting at the ZIP file? It really boils down to I don't really know where the ZIP file is being created.
