### ISSUE TITLE
'ZipDirectory' (1.1.4) is using deprecated task execution handler

### ISSUE THREAD

**Issue by jfsanchezaguilar** [XpiritBV/Xpirit.Vsts.Build.Zip#5]
From some time the hosted agent on VSTS is showing the following:

`##[warning]Task 'ZipDirectory' (1.1.4) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib`

Today it won't run:

`##[error]File not found: 'D:\a\_tasks\ZipDirectory_31f040e5-e040-4336-878a-59a473334433\1.2.0\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'`

Any workaround to keep using the task?

**Comment by pgroene** [comment]
Thank you for reporting the issue, I have update the extension to address this issue. If you still experience the issue, please leave a comment.
